### PR TITLE
Implement getBoards

### PR DESCRIPTION
**Pull request by grantsmith01**
Testing in Postman:

1. Find the ID of a workspace you want to test
2. Use the workspace ID in the request
3. Press send!

Screenshot 2023-10-31 at 4 20 40 PM

### CODE REVIEW

**Review by danielskjo — CHANGES_REQUESTED** [review]
Can you add a check to see if the user has access to the workspace? You had the code in your other pr

**Comment by danielskjo** [comment]
We also need to handle error if workspace doesnt exist

**Comment by grantsmith01** [comment]
> Can you add a check to see if the user has access to the workspace? You had the code in your other pr

Yeah, don't know why I forgot!

**Review by danielskjo — APPROVED** [review]
Lgtm

**Pull request merged**
